train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /home/gxk384/GaussianImage/DIV2K_train_HR
      repeat: 1
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 64
      scale_max: 4
      augment: true
      sample_q: 4096
      batch_per_gpu: 1
  batch_size: 1
val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /home/gxk384/GaussianImage/DIV2K_valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 64
      scale_max: 4
      sample_q: 4096
  batch_size: 1
data_norm:
  inp:
    sub:
    - 0.5
    div:
    - 0.5
  gt:
    sub:
    - 0.5
    div:
    - 0.5
model:
  name: gaussian-splatter
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    dec_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list:
        - 256
        - 256
        - 256
        - 256
    kernel_size: 5
optimizer:
  name: adam
  args:
    lr: 0.0001
epoch_max: 100
multi_step_lr:
  milestones:
  - 10
  - 20
  - 30
  - 40
  - 50
  - 60
  - 70
  - 80
  - 90
  gamma: 0.5
epoch_val: 1
epoch_save: 10
